services:
  - &base-config
    type: web
    name: render-env-test-staging
    env: static
    staticPublishPath: .
    pullRequestPreviewsEnabled: true
    branch: staging
    headers:
      - path: /*
        key: X-Foo
        value: generic x-foo
      - path: /*
        name: X-Bar
        value: staging x-bar-0

  - <<: *base-config
    name: render-env-test-prod
    pullRequestPreviewsEnabled: false
    branch: main
    headers:
      - path: /*
        name: X-Bar
        value: production x-bar-0
