services:
  - &BASE_CONFIG
    type: web
    name: render-env-test-staging
    env: static
    staticPublishPath: .
    pullRequestPreviewsEnabled: true
    branch: staging
    envVars:
      - key: X_BAR
        value: staging x-bar-0

  - <<: *BASE_CONFIG
    name: render-env-test-prod
    pullRequestPreviewsEnabled: false
    branch: main
    envVars:
      - key: X_BAR
        value: production x-bar-0
