services:
  - &BASE_CONFIG
    type: web
    name: render-env-test-staging
    env: static
    staticPublishPath: .
    pullRequestPreviewsEnabled: true
    branch: staging
    headers:
      - path: /*
        name: X-Foo
        value: staging-3
      - path: /*
        name: X-Bar
        value: staging-3

  - <<: *BASE_CONFIG
    name: render-env-test-prod
    pullRequestPreviewsEnabled: false
    branch: main
    headers:
      - path: /*
        name: X-Foo
        value: production-3
      - path: /*
        name: X-Bar
        value: production-3
