services:
  - type: web
    name: render-env-test-staging
    env: static
    staticPublishPath: .
    pullRequestPreviewsEnabled: true
    branch: staging
    headers:
      - path: /*
        name: X-Test
        value: staging x-test-3
    envVars:
      - key: TEST_1
        value: I'm special test 3

  - type: web
    name: render-env-test-prod
    env: static
    staticPublishPath: .
    pullRequestPreviewsEnabled: false
    branch: main
    headers:
      - path: /*
        name: X-Test
        value: production x-test
    envVars:
      - key: TEST_1
        value: I've changed test 2
