services:
  - &ENVVAR_1
    key: X_FOO
    value: generic x-foo
  - &base-config
    type: web
    name: render-env-test-staging
    env: static
    staticPublishPath: .
    pullRequestPreviewsEnabled: true
    branch: staging
    envVars:
      - <<: *ENVVAR_1
      - key: X_BAR
        value: staging x-bar-0

  - <<: *base-config
    name: render-env-test-prod
    pullRequestPreviewsEnabled: false
    branch: main
    envVars:
      - <<: *ENVVAR_1
      - key: X_BAR
        value: production x-bar-0
