services:
  - type: web
    name: render-env-test
    env: static
    staticPublishPath: .
    pullRequestPreviewsEnabled: true
    headers:
      - path: /*
        name: X-Foo
        value: staging-2
      - path: /*
        name: X-Bar
        value: staging
