services:
  type: web
  name: render-env-test
  env: static
  staticPublishPath: .
  pullRequestPreviewsEnabled: true
  branch: staging
  headers:
    - path: /*
      name: X-Foo
      value: staging
    - path: /*
      name: X-Bar
      value: staging
